<html>
    <head>
        <!DOCTYPE html>
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Include All from assets folder -->
        <?php include_once 'assets/headerLinks.phtml';?>
    </head>

    <body>
        <nav class="navbar-inverse navbar-default">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Roulette Calculator</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#">Home<span class="sr-only">(current)</span></a></li>
                        <li><a href="#">About</a></li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
        <div class="container">
            <div class="col-lg-4" id="div1">
                <h1>On a desktop, we take up 33% of the screen each! That's 4/12 columns!</h1>
                <p>
                    Bacon ipsum dolor amet doner turducken ball tip, drumstick ham beef ribs tenderloin frankfurter short ribs biltong shankle meatloaf sirloin rump capicola. Drumstick turkey ribeye capicola pork chop chuck rump sausage swine beef ribs shank bresaola doner tenderloin. Shank tongue prosciutto flank, beef ribs strip steak leberkas salami.
                    Turducken ground round pork belly short loin bresaola boudin.

                    Turducken tenderloin alcatra doner turkey, ball tip pancetta beef ground round rump pig swine.
                    Andouille pork belly meatloaf, leberkas pastrami jowl pig pork chop tenderloin tri-tip hamburger
                    filet mignon. Fatback strip steak cow beef shank hamburger biltong. Pork loin strip steak fatback,
                    prosciutto pancetta shoulder salami meatloaf. Cow tenderloin jowl capicola turkey.
                </p>
            </div>
            <div class="col-lg-4" id="div2">
                <h1>On a desktop, we take up 33% of the screen each! That's 4/12 columns!</h1>
                <p>
                    Bacon ipsum dolor amet doner turducken ball tip, drumstick ham beef ribs tenderloin frankfurter short ribs biltong shankle meatloaf sirloin rump capicola. Drumstick turkey ribeye capicola pork chop chuck rump sausage swine beef ribs shank bresaola doner tenderloin. Shank tongue prosciutto flank, beef ribs strip steak leberkas salami.
                    Turducken ground round pork belly short loin bresaola boudin.

                    Turducken tenderloin alcatra doner turkey, ball tip pancetta beef ground round rump pig swine.
                    Andouille pork belly meatloaf, leberkas pastrami jowl pig pork chop tenderloin tri-tip hamburger
                    filet mignon. Fatback strip steak cow beef shank hamburger biltong. Pork loin strip steak fatback,
                    prosciutto pancetta shoulder salami meatloaf. Cow tenderloin jowl capicola turkey.
                </p>
            </div>
            <div class="col-lg-4" id="div3">
                <h1>On a desktop, we take up 33% of the screen each! That's 4/12 columns!</h1>
                <p>
                    Bacon ipsum dolor amet doner turducken ball tip, drumstick ham beef ribs tenderloin frankfurter short ribs biltong shankle meatloaf sirloin rump capicola. Drumstick turkey ribeye capicola pork chop chuck rump sausage swine beef ribs shank bresaola doner tenderloin. Shank tongue prosciutto flank, beef ribs strip steak leberkas salami.
                    Turducken ground round pork belly short loin bresaola boudin.

                    Turducken tenderloin alcatra doner turkey, ball tip pancetta beef ground round rump pig swine.
                    Andouille pork belly meatloaf, leberkas pastrami jowl pig pork chop tenderloin tri-tip hamburger
                    filet mignon. Fatback strip steak cow beef shank hamburger biltong. Pork loin strip steak fatback,
                    prosciutto pancetta shoulder salami meatloaf. Cow tenderloin jowl capicola turkey.
                </p>
            </div>
            <div class="col-lg-12" id="div3">
                <h1>And I take up 100%! 12/12</h1>
                <p>
                    Bacon ipsum dolor amet doner turducken ball tip, drumstick ham beef ribs tenderloin frankfurter short ribs biltong shankle meatloaf sirloin rump capicola. Drumstick turkey ribeye capicola pork chop chuck rump sausage swine beef ribs shank bresaola doner tenderloin. Shank tongue prosciutto flank, beef ribs strip steak leberkas salami.
                    Turducken ground round pork belly short loin bresaola boudin.

                    Turducken tenderloin alcatra doner turkey, ball tip pancetta beef ground round rump pig swine.
                    Andouille pork belly meatloaf, leberkas pastrami jowl pig pork chop tenderloin tri-tip hamburger
                    filet mignon. Fatback strip steak cow beef shank hamburger biltong. Pork loin strip steak fatback,
                    prosciutto pancetta shoulder salami meatloaf. Cow tenderloin jowl capicola turkey.
                </p>
            </div>
            <img src="assets/img/header.jpg" class="img-responsive">

        </div>

    </body>
</html>

